name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: |
        cd android/
        chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        # 设置压缩文件的名称，在控制台会得到app-debug.zip文件的下载链接
        # 下载后解压缩，里面直接可以看到app-debug.apk，没有其他东西
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
